### ISSUE TITLE
CLI help doesn't work in 0.0.20 release

### ISSUE THREAD

**Issue by Luka958Pixion** [zilliztech/VectorDBBench#444]
- `MemoryDBHNSWTypedDict` raises exception

`vectordbbench --help`

```
Traceback (most recent call last):
  File "/home/my_username/VectorDBBench/venv/bin/vectordbbench", line 5, in <module>
    from vectordb_bench.cli.vectordbbench import cli
  File "/home/my_username/VectorDBBench/vectordb_bench/cli/vectordbbench.py", line 3, in <module>
    from ..backend.clients.memorydb.cli import MemoryDB
  File "/home/my_username/VectorDBBench/vectordb_bench/backend/clients/memorydb/cli.py", line 66, in <module>
    @click_parameter_decorators_from_typed_dict(MemoryDBHNSWTypedDict)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_username/VectorDBBench/vectordb_bench/cli/cli.py", line 103, in deco
    f = dec(f)
        ^^^^^^
  File "/home/my_username/VectorDBBench/venv/lib/python3.12/site-packages/click/decorators.py", line 365, in decorator
    _param_memo(f, cls(param_decls, **attrs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_username/VectorDBBench/venv/lib/python3.12/site-packages/click/core.py", line 2536, in __init__
    help = inspect.cleandoc(help)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/inspect.py", line 888, in cleandoc
    lines = doc.expandtabs().split('\n')
            ^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'expandtabs'
```

**Comment by XuanYang-cn** [comment]
working on fixing this

**Comment by XuanYang-cn** [comment]
should be fixed
